SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$begin
insert into public.user_profiles (
    id, 
    first_name, 
    last_name, 
    user_type, 
    language
  )
  values (
    new.id, 
    new.raw_user_meta_data ->> 'first_name', 
    new.raw_user_meta_data ->> 'last_name', 
    new.raw_user_meta_data ->> 'user_type', 
    new.raw_user_meta_data ->> 'language'
  );
  return new;
end;$$;

ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."connection_families_and_therapists" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "family_id" "uuid" NOT NULL,
    "therapist_id" "uuid" NOT NULL
);

ALTER TABLE "public"."connection_families_and_therapists" OWNER TO "postgres";

ALTER TABLE "public"."connection_families_and_therapists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."connection_families_and_therapists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."default_exercise_instructions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "images_urls" "text"[],
    "videos_urls" "text"[],
    "3d_animation_urls" "text"[]
);

ALTER TABLE "public"."default_exercise_instructions" OWNER TO "postgres";

ALTER TABLE "public"."default_exercise_instructions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."default_exercise_instructions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."default_exercises" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "thumbnail_url" "text",
    "duration_seconds_goal" smallint,
    "repetitions_goal" smallint,
    "default_scene_id" bigint NOT NULL,
    "focus_type" "text" DEFAULT ''::"text" NOT NULL,
    "possible_exercise_instructions" bigint[]
);

ALTER TABLE "public"."default_exercises" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."default_scenes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "images_urls" "text"[],
    "videos_urls" "text"[]
);

ALTER TABLE "public"."default_scenes" OWNER TO "postgres";

ALTER TABLE "public"."default_scenes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."default_scenes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."default_exercises" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exercises_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."families" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "patient_first_name" "text" NOT NULL,
    "patient_last_name" "text" NOT NULL,
    "uid" "uuid" NOT NULL,
    "caregiver_first_name" "text",
    "caregiver_last_name" "text",
    "therapist_uid" "uuid" NOT NULL
);

ALTER TABLE "public"."families" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."patient_achievements" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "vr_session_id" bigint NOT NULL,
    "exercise_id" bigint NOT NULL,
    "repetitions" smallint,
    "minutes" smallint,
    "patient_uid" "uuid"
);

ALTER TABLE "public"."patient_achievements" OWNER TO "postgres";

ALTER TABLE "public"."patient_achievements" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."patient_achievements_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."specialist_types" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."specialist_types" OWNER TO "postgres";

ALTER TABLE "public"."specialist_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."specialist_types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."therapists" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "specialist_type" "text" DEFAULT ''::"text",
    "prefix_phone_number" "text",
    "phone_number" "text",
    "country" "text",
    "street" "text",
    "street_number" "text",
    "postal_code" "text",
    "city" "text",
    "uid" "uuid" NOT NULL,
    "avatar_url" "text",
    "language" "text" DEFAULT 'de-CH'::"text"
);

ALTER TABLE "public"."therapists" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."training_block_exercises" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "training_block_id" bigint NOT NULL,
    "default_exercise_id" bigint NOT NULL,
    "duration_seconds_goal" smallint,
    "repetitions_goal" smallint,
    "focus_type" "text" DEFAULT ''::"text" NOT NULL,
    "family_scene_adjustment_access" boolean DEFAULT true NOT NULL,
    "therapist_uid" "uuid" NOT NULL,
    "training_unit_id" bigint NOT NULL,
    "name" "text" DEFAULT 'Exercise'::"text",
    "order_position" smallint NOT NULL
);

ALTER TABLE "public"."training_block_exercises" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."training_blocks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "order_position" integer NOT NULL,
    "patient_uid" "uuid",
    "therapist_uid" "uuid" NOT NULL,
    "training_unit_id" bigint NOT NULL
);

ALTER TABLE "public"."training_blocks" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."training_blocks_default_templates" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "order_position" integer NOT NULL
);

ALTER TABLE "public"."training_blocks_default_templates" OWNER TO "postgres";

COMMENT ON TABLE "public"."training_blocks_default_templates" IS 'This is a duplicate of training_blocks_therapist_templates';

ALTER TABLE "public"."training_blocks_default_templates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."training_blocks_default_templates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."training_blocks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."training_blocks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."training_blocks_therapist_templates" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "order_position" integer NOT NULL,
    "therapist_uid" "uuid" NOT NULL
);

ALTER TABLE "public"."training_blocks_therapist_templates" OWNER TO "postgres";

COMMENT ON TABLE "public"."training_blocks_therapist_templates" IS 'This is a duplicate of training_blocks';

ALTER TABLE "public"."training_blocks_therapist_templates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."training_blocks_therapist_templates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."training_block_exercises" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."training_plan_selected_exercises_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."training_units" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "patient_uid" "uuid" NOT NULL,
    "therapist_uid" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text"
);

ALTER TABLE "public"."training_units" OWNER TO "postgres";

ALTER TABLE "public"."training_units" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."training_units_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "id" "uuid" NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "user_type" "text",
    "language" "text"
);

ALTER TABLE "public"."user_profiles" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."vr_sessions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "patient_uid" "uuid"
);

ALTER TABLE "public"."vr_sessions" OWNER TO "postgres";

ALTER TABLE "public"."vr_sessions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."vr_sessions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."connection_families_and_therapists"
    ADD CONSTRAINT "connection_families_and_therapists_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."default_exercise_instructions"
    ADD CONSTRAINT "default_exercise_instructions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."default_scenes"
    ADD CONSTRAINT "default_scenes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."default_exercises"
    ADD CONSTRAINT "exercises_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."patient_achievements"
    ADD CONSTRAINT "patient_achievements_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."families"
    ADD CONSTRAINT "patients_pkey" PRIMARY KEY ("uid");

ALTER TABLE ONLY "public"."families"
    ADD CONSTRAINT "patients_uid_key" UNIQUE ("uid");

ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."specialist_types"
    ADD CONSTRAINT "specialist_types_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."specialist_types"
    ADD CONSTRAINT "specialist_types_pkey" PRIMARY KEY ("id", "name");

ALTER TABLE ONLY "public"."therapists"
    ADD CONSTRAINT "therapists_avatar_url_key" UNIQUE ("avatar_url");

ALTER TABLE ONLY "public"."therapists"
    ADD CONSTRAINT "therapists_pkey" PRIMARY KEY ("uid");

ALTER TABLE ONLY "public"."therapists"
    ADD CONSTRAINT "therapists_uid_key" UNIQUE ("uid");

ALTER TABLE ONLY "public"."training_blocks_default_templates"
    ADD CONSTRAINT "training_blocks_default_templates_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."training_blocks"
    ADD CONSTRAINT "training_blocks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."training_blocks_therapist_templates"
    ADD CONSTRAINT "training_blocks_therapist_templates_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."training_block_exercises"
    ADD CONSTRAINT "training_plan_selected_exercises_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."training_units"
    ADD CONSTRAINT "training_plans_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."vr_sessions"
    ADD CONSTRAINT "vr_sessions_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_training_plans_patient_id" ON "public"."training_units" USING "btree" ("patient_uid");

CREATE INDEX "idx_training_plans_patient_uid" ON "public"."training_units" USING "btree" ("patient_uid");

CREATE INDEX "idx_training_plans_therapist_uid" ON "public"."training_units" USING "btree" ("therapist_uid");

CREATE INDEX "idx_vr_sessions_patient_id" ON "public"."vr_sessions" USING "btree" ("patient_uid");

CREATE INDEX "idx_vr_sessions_patient_uid" ON "public"."vr_sessions" USING "btree" ("patient_uid");

ALTER TABLE ONLY "public"."patient_achievements"
    ADD CONSTRAINT "patient_achievements_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "public"."default_exercises"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."patient_achievements"
    ADD CONSTRAINT "patient_achievements_patient_uid_fkey" FOREIGN KEY ("patient_uid") REFERENCES "public"."families"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."patient_achievements"
    ADD CONSTRAINT "patient_achievements_vr_session_id_fkey" FOREIGN KEY ("vr_session_id") REFERENCES "public"."vr_sessions"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."families"
    ADD CONSTRAINT "patients_uid_fkey" FOREIGN KEY ("uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."connection_families_and_therapists"
    ADD CONSTRAINT "public_connection_families_and_therapists_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."connection_families_and_therapists"
    ADD CONSTRAINT "public_connection_families_and_therapists_therapist_id_fkey" FOREIGN KEY ("therapist_id") REFERENCES "public"."therapists"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."default_exercises"
    ADD CONSTRAINT "public_default_exercises_default_scene_id_fkey" FOREIGN KEY ("default_scene_id") REFERENCES "public"."default_scenes"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."families"
    ADD CONSTRAINT "public_families_therapist_uid_fkey" FOREIGN KEY ("therapist_uid") REFERENCES "public"."therapists"("uid");

ALTER TABLE ONLY "public"."training_block_exercises"
    ADD CONSTRAINT "public_training_block_exercises_default_exercise_id_fkey" FOREIGN KEY ("default_exercise_id") REFERENCES "public"."default_exercises"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_block_exercises"
    ADD CONSTRAINT "public_training_block_exercises_therapist_uid_fkey" FOREIGN KEY ("therapist_uid") REFERENCES "public"."therapists"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_block_exercises"
    ADD CONSTRAINT "public_training_block_exercises_training_block_id_fkey" FOREIGN KEY ("training_block_id") REFERENCES "public"."training_blocks"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_block_exercises"
    ADD CONSTRAINT "public_training_block_exercises_training_unit_id_fkey" FOREIGN KEY ("training_unit_id") REFERENCES "public"."training_units"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_blocks"
    ADD CONSTRAINT "public_training_blocks_patient_uid_fkey" FOREIGN KEY ("patient_uid") REFERENCES "public"."families"("uid") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."training_blocks_therapist_templates"
    ADD CONSTRAINT "public_training_blocks_therapist_templates_therapist_uid_fkey" FOREIGN KEY ("therapist_uid") REFERENCES "public"."therapists"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_blocks"
    ADD CONSTRAINT "public_training_blocks_therapist_uid_fkey" FOREIGN KEY ("therapist_uid") REFERENCES "public"."therapists"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_blocks"
    ADD CONSTRAINT "public_training_blocks_training_plan_id_fkey" FOREIGN KEY ("training_unit_id") REFERENCES "public"."training_units"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."therapists"
    ADD CONSTRAINT "therapists_uid_fkey" FOREIGN KEY ("uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_units"
    ADD CONSTRAINT "training_plans_patient_id_fkey" FOREIGN KEY ("patient_uid") REFERENCES "public"."families"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."training_units"
    ADD CONSTRAINT "training_plans_therapist_id_fkey" FOREIGN KEY ("therapist_uid") REFERENCES "public"."therapists"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."vr_sessions"
    ADD CONSTRAINT "vr_sessions_patient_id_fkey" FOREIGN KEY ("patient_uid") REFERENCES "public"."families"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

CREATE POLICY "Enable insert for users based on therapist_uid" ON "public"."training_block_exercises" FOR INSERT WITH CHECK (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable insert for users based on therapist_uid" ON "public"."training_blocks" FOR INSERT WITH CHECK (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable insert for users based on therapist_uid" ON "public"."training_units" FOR INSERT WITH CHECK (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable read access for all users" ON "public"."default_scenes" FOR SELECT USING (true);

CREATE POLICY "Enable select for users based on therapist_uid" ON "public"."training_block_exercises" FOR SELECT USING (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable select for users based on therapist_uid" ON "public"."training_blocks" FOR SELECT USING (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable select for users based on therapist_uid" ON "public"."training_units" FOR SELECT USING (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable update for users based on therapist_uid" ON "public"."training_block_exercises" FOR UPDATE USING (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable update for users based on therapist_uid" ON "public"."training_blocks" FOR UPDATE USING (("auth"."uid"() = "therapist_uid"));

CREATE POLICY "Enable update for users based on therapist_uid" ON "public"."training_units" FOR UPDATE USING (("auth"."uid"() = "therapist_uid"));

ALTER TABLE "public"."connection_families_and_therapists" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."default_exercise_instructions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."default_exercises" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."default_scenes" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."families" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."patient_achievements" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."specialist_types" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."therapists" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."training_block_exercises" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."training_blocks" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."training_blocks_default_templates" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."training_blocks_therapist_templates" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."training_units" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."vr_sessions" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";

GRANT ALL ON TABLE "public"."connection_families_and_therapists" TO "anon";
GRANT ALL ON TABLE "public"."connection_families_and_therapists" TO "authenticated";
GRANT ALL ON TABLE "public"."connection_families_and_therapists" TO "service_role";

GRANT ALL ON SEQUENCE "public"."connection_families_and_therapists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."connection_families_and_therapists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."connection_families_and_therapists_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."default_exercise_instructions" TO "anon";
GRANT ALL ON TABLE "public"."default_exercise_instructions" TO "authenticated";
GRANT ALL ON TABLE "public"."default_exercise_instructions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."default_exercise_instructions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."default_exercise_instructions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."default_exercise_instructions_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."default_exercises" TO "anon";
GRANT ALL ON TABLE "public"."default_exercises" TO "authenticated";
GRANT ALL ON TABLE "public"."default_exercises" TO "service_role";

GRANT ALL ON TABLE "public"."default_scenes" TO "anon";
GRANT ALL ON TABLE "public"."default_scenes" TO "authenticated";
GRANT ALL ON TABLE "public"."default_scenes" TO "service_role";

GRANT ALL ON SEQUENCE "public"."default_scenes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."default_scenes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."default_scenes_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."exercises_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exercises_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exercises_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."families" TO "anon";
GRANT ALL ON TABLE "public"."families" TO "authenticated";
GRANT ALL ON TABLE "public"."families" TO "service_role";

GRANT ALL ON TABLE "public"."patient_achievements" TO "anon";
GRANT ALL ON TABLE "public"."patient_achievements" TO "authenticated";
GRANT ALL ON TABLE "public"."patient_achievements" TO "service_role";

GRANT ALL ON SEQUENCE "public"."patient_achievements_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."patient_achievements_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."patient_achievements_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."specialist_types" TO "anon";
GRANT ALL ON TABLE "public"."specialist_types" TO "authenticated";
GRANT ALL ON TABLE "public"."specialist_types" TO "service_role";

GRANT ALL ON SEQUENCE "public"."specialist_types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."specialist_types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."specialist_types_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."therapists" TO "anon";
GRANT ALL ON TABLE "public"."therapists" TO "authenticated";
GRANT ALL ON TABLE "public"."therapists" TO "service_role";

GRANT ALL ON TABLE "public"."training_block_exercises" TO "anon";
GRANT ALL ON TABLE "public"."training_block_exercises" TO "authenticated";
GRANT ALL ON TABLE "public"."training_block_exercises" TO "service_role";

GRANT ALL ON TABLE "public"."training_blocks" TO "anon";
GRANT ALL ON TABLE "public"."training_blocks" TO "authenticated";
GRANT ALL ON TABLE "public"."training_blocks" TO "service_role";

GRANT ALL ON TABLE "public"."training_blocks_default_templates" TO "anon";
GRANT ALL ON TABLE "public"."training_blocks_default_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."training_blocks_default_templates" TO "service_role";

GRANT ALL ON SEQUENCE "public"."training_blocks_default_templates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."training_blocks_default_templates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."training_blocks_default_templates_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."training_blocks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."training_blocks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."training_blocks_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."training_blocks_therapist_templates" TO "anon";
GRANT ALL ON TABLE "public"."training_blocks_therapist_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."training_blocks_therapist_templates" TO "service_role";

GRANT ALL ON SEQUENCE "public"."training_blocks_therapist_templates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."training_blocks_therapist_templates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."training_blocks_therapist_templates_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."training_plan_selected_exercises_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."training_plan_selected_exercises_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."training_plan_selected_exercises_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."training_units" TO "anon";
GRANT ALL ON TABLE "public"."training_units" TO "authenticated";
GRANT ALL ON TABLE "public"."training_units" TO "service_role";

GRANT ALL ON SEQUENCE "public"."training_units_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."training_units_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."training_units_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."user_profiles" TO "anon";
GRANT ALL ON TABLE "public"."user_profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_profiles" TO "service_role";

GRANT ALL ON TABLE "public"."vr_sessions" TO "anon";
GRANT ALL ON TABLE "public"."vr_sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."vr_sessions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."vr_sessions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vr_sessions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vr_sessions_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;