export const useExerciseStateMachine = () => {
};

[
    {
        "id": "575cd2db-bee3-41d0-adde-d1af310ae4fa",
        "name": "Hanteln linker Arm",
        "results": {},
        "created_at": "2025-04-22T17:24:04.342Z",
        "focus_type": "balance",
        "description":
            "Bewege die Hantel fünf mal hoch und runter mit deinem Linken Arm.",
        "is_template": true,
        "exercise_type": "exercise_screen",
        "therapist_uid": "365a3487-0b98-4443-be87-df78c3bb5537",
        "repetitions_goal": 5,
        "duration_seconds_goal": null,
        "exercise_instruction_ids": null,
        "inherited_default_exercise": null,
        "therapist_added_image_urls": null,
        "therapist_added_video_urls": null,
        "family_scene_adjustment_access": false,
        "unitID": "34cac52f-8c90-479b-bf21-96fa40fdf3fd",
        "completed_status": "none",
    },
    {
        "id": "52349c3a-dcfd-4256-872b-73f40e2457ad",
        "name": "Beweglichkeit Linkes Bein",
        "results": {},
        "created_at": "2025-04-22T17:24:04.342Z",
        "focus_type": "range-of-motion",
        "description":
            "Ein Test um die Beweglichkeit des linken beins zu testen",
        "is_template": null,
        "exercise_type": "exercise_screen",
        "therapist_uid": "365a3487-0b98-4443-be87-df78c3bb5537",
        "repetitions_goal": 3,
        "duration_seconds_goal": null,
        "exercise_instruction_ids": null,
        "inherited_default_exercise": null,
        "therapist_added_image_urls": null,
        "therapist_added_video_urls": null,
        "family_scene_adjustment_access": false,
        "unitID": "34cac52f-8c90-479b-bf21-96fa40fdf3fd",
        "completed_status": "none",
    },
    {
        "id": "952a62ab-5130-4088-b415-a97d0394751e",
        "name": "Beweglichkeit Linke Hüftseite",
        "results": {},
        "created_at": "2025-04-22T17:24:04.342Z",
        "focus_type": "range-of-motion",
        "description": "Test für die Beweglichkeit der linken Hüftseite.",
        "is_template": null,
        "exercise_type": "exercise_screen",
        "therapist_uid": "365a3487-0b98-4443-be87-df78c3bb5537",
        "repetitions_goal": 3,
        "duration_seconds_goal": null,
        "exercise_instruction_ids": null,
        "inherited_default_exercise": null,
        "therapist_added_image_urls": null,
        "therapist_added_video_urls": null,
        "family_scene_adjustment_access": true,
        "unitID": "34cac52f-8c90-479b-bf21-96fa40fdf3fd",
        "completed_status": "none",
    },
    {
        "id": "cd7fbad2-1bc3-4c23-9f8e-0146233f441f",
        "name": "Balance Full Tandem",
        "results": {},
        "created_at": "2025-04-22T17:24:04.342Z",
        "focus_type": "balance",
        "description":
            "Versuche eine Minute mit den Füssen voreinander balanciert zu bleiben",
        "is_template": false,
        "exercise_type": "exercise_screen",
        "therapist_uid": "365a3487-0b98-4443-be87-df78c3bb5537",
        "repetitions_goal": null,
        "duration_seconds_goal": 60,
        "exercise_instruction_ids": null,
        "inherited_default_exercise": null,
        "therapist_added_image_urls": null,
        "therapist_added_video_urls": null,
        "family_scene_adjustment_access": false,
        "unitID": "34cac52f-8c90-479b-bf21-96fa40fdf3fd",
        "completed_status": "none",
    },
];
