create type "public"."exercise_type" as enum ('exercise_screen', 'exericse_vr', 'assessment_screen', 'assessment_vr');

create table "public"."exercise_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "data" jsonb not null
);

alter table "public"."exercise_categories" enable row level security;

alter table "public"."default_assessments" drop column "modality";

alter table "public"."default_exercises" drop column "modality";

alter table "public"."exercises" drop column "modality";

alter table "public"."exercises" add column "data" jsonb;

alter table "public"."exercises"
add column "exercise_type" exercise_type not null default 'exercise_screen'::exercise_type;

drop type "public"."modality";

CREATE UNIQUE INDEX exercise_categories_pkey ON public.exercise_categories USING btree (id);

alter table "public"."exercise_categories"
add constraint "exercise_categories_pkey" PRIMARY KEY using index "exercise_categories_pkey";

grant delete on table "public"."exercise_categories" to "anon";

grant insert on table "public"."exercise_categories" to "anon";

grant references on table "public"."exercise_categories" to "anon";

grant select on table "public"."exercise_categories" to "anon";

grant trigger on table "public"."exercise_categories" to "anon";

grant truncate on table "public"."exercise_categories" to "anon";

grant update on table "public"."exercise_categories" to "anon";

grant delete on table "public"."exercise_categories" to "authenticated";

grant insert on table "public"."exercise_categories" to "authenticated";

grant references on table "public"."exercise_categories" to "authenticated";

grant
select on table "public"."exercise_categories" to "authenticated";

grant trigger on table "public"."exercise_categories" to "authenticated";

grant
truncate on table "public"."exercise_categories" to "authenticated";

grant
update on table "public"."exercise_categories" to "authenticated";

grant delete on table "public"."exercise_categories" to "service_role";

grant insert on table "public"."exercise_categories" to "service_role";

grant references on table "public"."exercise_categories" to "service_role";

grant
select on table "public"."exercise_categories" to "service_role";

grant trigger on table "public"."exercise_categories" to "service_role";

grant
truncate on table "public"."exercise_categories" to "service_role";

grant
update on table "public"."exercise_categories" to "service_role";