drop policy "Enable read access for all users" on "public"."profiles";

revoke delete on table "public"."profiles" from "anon";

revoke insert on table "public"."profiles" from "anon";

revoke references on table "public"."profiles" from "anon";

revoke select on table "public"."profiles" from "anon";

revoke trigger on table "public"."profiles" from "anon";

revoke truncate on table "public"."profiles" from "anon";

revoke update on table "public"."profiles" from "anon";

revoke delete on table "public"."profiles" from "authenticated";

revoke insert on table "public"."profiles" from "authenticated";

revoke references on table "public"."profiles" from "authenticated";

revoke select on table "public"."profiles" from "authenticated";

revoke trigger on table "public"."profiles" from "authenticated";

revoke truncate on table "public"."profiles" from "authenticated";

revoke update on table "public"."profiles" from "authenticated";

revoke delete on table "public"."profiles" from "service_role";

revoke insert on table "public"."profiles" from "service_role";

revoke references on table "public"."profiles" from "service_role";

revoke select on table "public"."profiles" from "service_role";

revoke trigger on table "public"."profiles" from "service_role";

revoke truncate on table "public"."profiles" from "service_role";

revoke update on table "public"."profiles" from "service_role";

alter table "public"."profiles" drop constraint "profiles_pkey";

drop index if exists "public"."profiles_pkey";

drop table "public"."profiles";

create table "public"."exercises" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text not null,
    "images_urls" text[],
    "videos_urls" text[],
    "therapist_id" bigint not null
);


alter table "public"."exercises" enable row level security;

create table "public"."patient_achievements" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "vr_session_id" bigint not null,
    "exercise_id" bigint not null,
    "repetitions" smallint,
    "minutes" smallint
);


alter table "public"."patient_achievements" enable row level security;

create table "public"."patients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text not null,
    "last_name" text not null,
    "condition_gmfcs" smallint,
    "therapist_id" bigint not null
);


alter table "public"."patients" enable row level security;

create table "public"."specialist_types" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."specialist_types" enable row level security;

create table "public"."therapists" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text not null,
    "last_name" text not null,
    "specialist_type" text not null default ''::text,
    "email" text not null,
    "prefix_phone_number" text,
    "phone_number" text,
    "country" text,
    "street" text,
    "street_number" text,
    "postal_code" text,
    "city" text
);


alter table "public"."therapists" enable row level security;

create table "public"."training_plan_selected_exercises" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "training_plan_id" bigint not null,
    "exercise_id" bigint not null,
    "duration_minutes" smallint,
    "repetitions" smallint,
    "physical_location" text,
    "vr_location" text
);


alter table "public"."training_plan_selected_exercises" enable row level security;

create table "public"."training_plans" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "patient_id" bigint not null,
    "therapist_id" bigint not null
);


alter table "public"."training_plans" enable row level security;

create table "public"."vr_sessions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "patient_id" bigint not null
);


alter table "public"."vr_sessions" enable row level security;

CREATE UNIQUE INDEX exercises_pkey ON public.exercises USING btree (id);

CREATE UNIQUE INDEX patient_achievements_pkey ON public.patient_achievements USING btree (id);

CREATE UNIQUE INDEX patients_pkey ON public.patients USING btree (id);

CREATE UNIQUE INDEX specialist_types_name_key ON public.specialist_types USING btree (name);

CREATE UNIQUE INDEX specialist_types_pkey ON public.specialist_types USING btree (id, name);

CREATE UNIQUE INDEX therapists_pkey ON public.therapists USING btree (id);

CREATE UNIQUE INDEX training_plan_selected_exercises_pkey ON public.training_plan_selected_exercises USING btree (id);

CREATE UNIQUE INDEX training_plans_pkey ON public.training_plans USING btree (id);

CREATE UNIQUE INDEX vr_sessions_pkey ON public.vr_sessions USING btree (id);

alter table "public"."exercises" add constraint "exercises_pkey" PRIMARY KEY using index "exercises_pkey";

alter table "public"."patient_achievements" add constraint "patient_achievements_pkey" PRIMARY KEY using index "patient_achievements_pkey";

alter table "public"."patients" add constraint "patients_pkey" PRIMARY KEY using index "patients_pkey";

alter table "public"."specialist_types" add constraint "specialist_types_pkey" PRIMARY KEY using index "specialist_types_pkey";

alter table "public"."therapists" add constraint "therapists_pkey" PRIMARY KEY using index "therapists_pkey";

alter table "public"."training_plan_selected_exercises" add constraint "training_plan_selected_exercises_pkey" PRIMARY KEY using index "training_plan_selected_exercises_pkey";

alter table "public"."training_plans" add constraint "training_plans_pkey" PRIMARY KEY using index "training_plans_pkey";

alter table "public"."vr_sessions" add constraint "vr_sessions_pkey" PRIMARY KEY using index "vr_sessions_pkey";

alter table "public"."exercises" add constraint "exercises_therapist_id_fkey" FOREIGN KEY (therapist_id) REFERENCES therapists(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."exercises" validate constraint "exercises_therapist_id_fkey";

alter table "public"."patient_achievements" add constraint "patient_achievements_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."patient_achievements" validate constraint "patient_achievements_exercise_id_fkey";

alter table "public"."patient_achievements" add constraint "patient_achievements_vr_session_id_fkey" FOREIGN KEY (vr_session_id) REFERENCES vr_sessions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."patient_achievements" validate constraint "patient_achievements_vr_session_id_fkey";

alter table "public"."patients" add constraint "patients_condition_gmfcs_check" CHECK (((condition_gmfcs > 0) AND (condition_gmfcs <= 5))) not valid;

alter table "public"."patients" validate constraint "patients_condition_gmfcs_check";

alter table "public"."patients" add constraint "patients_therapist_id_fkey" FOREIGN KEY (therapist_id) REFERENCES therapists(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."patients" validate constraint "patients_therapist_id_fkey";

alter table "public"."specialist_types" add constraint "specialist_types_name_key" UNIQUE using index "specialist_types_name_key";

alter table "public"."therapists" add constraint "therapists_specialist_type_fkey" FOREIGN KEY (specialist_type) REFERENCES specialist_types(name) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."therapists" validate constraint "therapists_specialist_type_fkey";

alter table "public"."training_plan_selected_exercises" add constraint "training_plan_selected_exercises_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."training_plan_selected_exercises" validate constraint "training_plan_selected_exercises_exercise_id_fkey";

alter table "public"."training_plan_selected_exercises" add constraint "training_plan_selected_exercises_training_plan_id_fkey" FOREIGN KEY (training_plan_id) REFERENCES training_plans(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."training_plan_selected_exercises" validate constraint "training_plan_selected_exercises_training_plan_id_fkey";

alter table "public"."training_plans" add constraint "training_plans_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES patients(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."training_plans" validate constraint "training_plans_patient_id_fkey";

alter table "public"."training_plans" add constraint "training_plans_therapist_id_fkey" FOREIGN KEY (therapist_id) REFERENCES therapists(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."training_plans" validate constraint "training_plans_therapist_id_fkey";

alter table "public"."vr_sessions" add constraint "vr_sessions_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES patients(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vr_sessions" validate constraint "vr_sessions_patient_id_fkey";

grant delete on table "public"."exercises" to "anon";

grant insert on table "public"."exercises" to "anon";

grant references on table "public"."exercises" to "anon";

grant select on table "public"."exercises" to "anon";

grant trigger on table "public"."exercises" to "anon";

grant truncate on table "public"."exercises" to "anon";

grant update on table "public"."exercises" to "anon";

grant delete on table "public"."exercises" to "authenticated";

grant insert on table "public"."exercises" to "authenticated";

grant references on table "public"."exercises" to "authenticated";

grant select on table "public"."exercises" to "authenticated";

grant trigger on table "public"."exercises" to "authenticated";

grant truncate on table "public"."exercises" to "authenticated";

grant update on table "public"."exercises" to "authenticated";

grant delete on table "public"."exercises" to "service_role";

grant insert on table "public"."exercises" to "service_role";

grant references on table "public"."exercises" to "service_role";

grant select on table "public"."exercises" to "service_role";

grant trigger on table "public"."exercises" to "service_role";

grant truncate on table "public"."exercises" to "service_role";

grant update on table "public"."exercises" to "service_role";

grant delete on table "public"."patient_achievements" to "anon";

grant insert on table "public"."patient_achievements" to "anon";

grant references on table "public"."patient_achievements" to "anon";

grant select on table "public"."patient_achievements" to "anon";

grant trigger on table "public"."patient_achievements" to "anon";

grant truncate on table "public"."patient_achievements" to "anon";

grant update on table "public"."patient_achievements" to "anon";

grant delete on table "public"."patient_achievements" to "authenticated";

grant insert on table "public"."patient_achievements" to "authenticated";

grant references on table "public"."patient_achievements" to "authenticated";

grant select on table "public"."patient_achievements" to "authenticated";

grant trigger on table "public"."patient_achievements" to "authenticated";

grant truncate on table "public"."patient_achievements" to "authenticated";

grant update on table "public"."patient_achievements" to "authenticated";

grant delete on table "public"."patient_achievements" to "service_role";

grant insert on table "public"."patient_achievements" to "service_role";

grant references on table "public"."patient_achievements" to "service_role";

grant select on table "public"."patient_achievements" to "service_role";

grant trigger on table "public"."patient_achievements" to "service_role";

grant truncate on table "public"."patient_achievements" to "service_role";

grant update on table "public"."patient_achievements" to "service_role";

grant delete on table "public"."patients" to "anon";

grant insert on table "public"."patients" to "anon";

grant references on table "public"."patients" to "anon";

grant select on table "public"."patients" to "anon";

grant trigger on table "public"."patients" to "anon";

grant truncate on table "public"."patients" to "anon";

grant update on table "public"."patients" to "anon";

grant delete on table "public"."patients" to "authenticated";

grant insert on table "public"."patients" to "authenticated";

grant references on table "public"."patients" to "authenticated";

grant select on table "public"."patients" to "authenticated";

grant trigger on table "public"."patients" to "authenticated";

grant truncate on table "public"."patients" to "authenticated";

grant update on table "public"."patients" to "authenticated";

grant delete on table "public"."patients" to "service_role";

grant insert on table "public"."patients" to "service_role";

grant references on table "public"."patients" to "service_role";

grant select on table "public"."patients" to "service_role";

grant trigger on table "public"."patients" to "service_role";

grant truncate on table "public"."patients" to "service_role";

grant update on table "public"."patients" to "service_role";

grant delete on table "public"."specialist_types" to "anon";

grant insert on table "public"."specialist_types" to "anon";

grant references on table "public"."specialist_types" to "anon";

grant select on table "public"."specialist_types" to "anon";

grant trigger on table "public"."specialist_types" to "anon";

grant truncate on table "public"."specialist_types" to "anon";

grant update on table "public"."specialist_types" to "anon";

grant delete on table "public"."specialist_types" to "authenticated";

grant insert on table "public"."specialist_types" to "authenticated";

grant references on table "public"."specialist_types" to "authenticated";

grant select on table "public"."specialist_types" to "authenticated";

grant trigger on table "public"."specialist_types" to "authenticated";

grant truncate on table "public"."specialist_types" to "authenticated";

grant update on table "public"."specialist_types" to "authenticated";

grant delete on table "public"."specialist_types" to "service_role";

grant insert on table "public"."specialist_types" to "service_role";

grant references on table "public"."specialist_types" to "service_role";

grant select on table "public"."specialist_types" to "service_role";

grant trigger on table "public"."specialist_types" to "service_role";

grant truncate on table "public"."specialist_types" to "service_role";

grant update on table "public"."specialist_types" to "service_role";

grant delete on table "public"."therapists" to "anon";

grant insert on table "public"."therapists" to "anon";

grant references on table "public"."therapists" to "anon";

grant select on table "public"."therapists" to "anon";

grant trigger on table "public"."therapists" to "anon";

grant truncate on table "public"."therapists" to "anon";

grant update on table "public"."therapists" to "anon";

grant delete on table "public"."therapists" to "authenticated";

grant insert on table "public"."therapists" to "authenticated";

grant references on table "public"."therapists" to "authenticated";

grant select on table "public"."therapists" to "authenticated";

grant trigger on table "public"."therapists" to "authenticated";

grant truncate on table "public"."therapists" to "authenticated";

grant update on table "public"."therapists" to "authenticated";

grant delete on table "public"."therapists" to "service_role";

grant insert on table "public"."therapists" to "service_role";

grant references on table "public"."therapists" to "service_role";

grant select on table "public"."therapists" to "service_role";

grant trigger on table "public"."therapists" to "service_role";

grant truncate on table "public"."therapists" to "service_role";

grant update on table "public"."therapists" to "service_role";

grant delete on table "public"."training_plan_selected_exercises" to "anon";

grant insert on table "public"."training_plan_selected_exercises" to "anon";

grant references on table "public"."training_plan_selected_exercises" to "anon";

grant select on table "public"."training_plan_selected_exercises" to "anon";

grant trigger on table "public"."training_plan_selected_exercises" to "anon";

grant truncate on table "public"."training_plan_selected_exercises" to "anon";

grant update on table "public"."training_plan_selected_exercises" to "anon";

grant delete on table "public"."training_plan_selected_exercises" to "authenticated";

grant insert on table "public"."training_plan_selected_exercises" to "authenticated";

grant references on table "public"."training_plan_selected_exercises" to "authenticated";

grant select on table "public"."training_plan_selected_exercises" to "authenticated";

grant trigger on table "public"."training_plan_selected_exercises" to "authenticated";

grant truncate on table "public"."training_plan_selected_exercises" to "authenticated";

grant update on table "public"."training_plan_selected_exercises" to "authenticated";

grant delete on table "public"."training_plan_selected_exercises" to "service_role";

grant insert on table "public"."training_plan_selected_exercises" to "service_role";

grant references on table "public"."training_plan_selected_exercises" to "service_role";

grant select on table "public"."training_plan_selected_exercises" to "service_role";

grant trigger on table "public"."training_plan_selected_exercises" to "service_role";

grant truncate on table "public"."training_plan_selected_exercises" to "service_role";

grant update on table "public"."training_plan_selected_exercises" to "service_role";

grant delete on table "public"."training_plans" to "anon";

grant insert on table "public"."training_plans" to "anon";

grant references on table "public"."training_plans" to "anon";

grant select on table "public"."training_plans" to "anon";

grant trigger on table "public"."training_plans" to "anon";

grant truncate on table "public"."training_plans" to "anon";

grant update on table "public"."training_plans" to "anon";

grant delete on table "public"."training_plans" to "authenticated";

grant insert on table "public"."training_plans" to "authenticated";

grant references on table "public"."training_plans" to "authenticated";

grant select on table "public"."training_plans" to "authenticated";

grant trigger on table "public"."training_plans" to "authenticated";

grant truncate on table "public"."training_plans" to "authenticated";

grant update on table "public"."training_plans" to "authenticated";

grant delete on table "public"."training_plans" to "service_role";

grant insert on table "public"."training_plans" to "service_role";

grant references on table "public"."training_plans" to "service_role";

grant select on table "public"."training_plans" to "service_role";

grant trigger on table "public"."training_plans" to "service_role";

grant truncate on table "public"."training_plans" to "service_role";

grant update on table "public"."training_plans" to "service_role";

grant delete on table "public"."vr_sessions" to "anon";

grant insert on table "public"."vr_sessions" to "anon";

grant references on table "public"."vr_sessions" to "anon";

grant select on table "public"."vr_sessions" to "anon";

grant trigger on table "public"."vr_sessions" to "anon";

grant truncate on table "public"."vr_sessions" to "anon";

grant update on table "public"."vr_sessions" to "anon";

grant delete on table "public"."vr_sessions" to "authenticated";

grant insert on table "public"."vr_sessions" to "authenticated";

grant references on table "public"."vr_sessions" to "authenticated";

grant select on table "public"."vr_sessions" to "authenticated";

grant trigger on table "public"."vr_sessions" to "authenticated";

grant truncate on table "public"."vr_sessions" to "authenticated";

grant update on table "public"."vr_sessions" to "authenticated";

grant delete on table "public"."vr_sessions" to "service_role";

grant insert on table "public"."vr_sessions" to "service_role";

grant references on table "public"."vr_sessions" to "service_role";

grant select on table "public"."vr_sessions" to "service_role";

grant trigger on table "public"."vr_sessions" to "service_role";

grant truncate on table "public"."vr_sessions" to "service_role";

grant update on table "public"."vr_sessions" to "service_role";


