revoke delete on table "public"."patient_records" from "anon";

revoke insert on table "public"."patient_records" from "anon";

revoke references on table "public"."patient_records" from "anon";

revoke select on table "public"."patient_records" from "anon";

revoke trigger on table "public"."patient_records" from "anon";

revoke truncate on table "public"."patient_records" from "anon";

revoke update on table "public"."patient_records" from "anon";

revoke delete on table "public"."patient_records" from "authenticated";

revoke insert on table "public"."patient_records" from "authenticated";

revoke references on table "public"."patient_records" from "authenticated";

revoke select on table "public"."patient_records" from "authenticated";

revoke trigger on table "public"."patient_records" from "authenticated";

revoke truncate on table "public"."patient_records" from "authenticated";

revoke update on table "public"."patient_records" from "authenticated";

revoke delete on table "public"."patient_records" from "service_role";

revoke insert on table "public"."patient_records" from "service_role";

revoke references on table "public"."patient_records" from "service_role";

revoke select on table "public"."patient_records" from "service_role";

revoke trigger on table "public"."patient_records" from "service_role";

revoke truncate on table "public"."patient_records" from "service_role";

revoke update on table "public"."patient_records" from "service_role";

alter table "public"."patient_records" drop constraint "patient_achievements_patient_uid_fkey";

alter table "public"."patient_records" drop constraint "patient_achievements_vr_session_id_fkey";

alter table "public"."patient_records" drop constraint "patient_achievements_pkey";

drop index if exists "public"."patient_achievements_pkey";

drop table "public"."patient_records";

create table "public"."patient_exercise_records" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "session_id" bigint not null,
    "patient_uid" uuid not null,
    "type" record_types not null,
    "data" jsonb not null,
    "exercise_id" uuid not null
);


alter table "public"."patient_exercise_records" enable row level security;

CREATE UNIQUE INDEX patient_achievements_pkey ON public.patient_exercise_records USING btree (id);

alter table "public"."patient_exercise_records" add constraint "patient_achievements_pkey" PRIMARY KEY using index "patient_achievements_pkey";

alter table "public"."patient_exercise_records" add constraint "patient_achievements_patient_uid_fkey" FOREIGN KEY (patient_uid) REFERENCES families(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."patient_exercise_records" validate constraint "patient_achievements_patient_uid_fkey";

alter table "public"."patient_exercise_records" add constraint "patient_achievements_vr_session_id_fkey" FOREIGN KEY (session_id) REFERENCES patient_sessions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."patient_exercise_records" validate constraint "patient_achievements_vr_session_id_fkey";

alter table "public"."patient_exercise_records" add constraint "public_patient_exercise_records_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."patient_exercise_records" validate constraint "public_patient_exercise_records_exercise_id_fkey";

grant delete on table "public"."patient_exercise_records" to "anon";

grant insert on table "public"."patient_exercise_records" to "anon";

grant references on table "public"."patient_exercise_records" to "anon";

grant select on table "public"."patient_exercise_records" to "anon";

grant trigger on table "public"."patient_exercise_records" to "anon";

grant truncate on table "public"."patient_exercise_records" to "anon";

grant update on table "public"."patient_exercise_records" to "anon";

grant delete on table "public"."patient_exercise_records" to "authenticated";

grant insert on table "public"."patient_exercise_records" to "authenticated";

grant references on table "public"."patient_exercise_records" to "authenticated";

grant select on table "public"."patient_exercise_records" to "authenticated";

grant trigger on table "public"."patient_exercise_records" to "authenticated";

grant truncate on table "public"."patient_exercise_records" to "authenticated";

grant update on table "public"."patient_exercise_records" to "authenticated";

grant delete on table "public"."patient_exercise_records" to "service_role";

grant insert on table "public"."patient_exercise_records" to "service_role";

grant references on table "public"."patient_exercise_records" to "service_role";

grant select on table "public"."patient_exercise_records" to "service_role";

grant trigger on table "public"."patient_exercise_records" to "service_role";

grant truncate on table "public"."patient_exercise_records" to "service_role";

grant update on table "public"."patient_exercise_records" to "service_role";