create type "public"."exercise_modality" as enum ('assessment', 'virtual-reality', 'video-instruction', 'other');

create table "public"."default_exercise_instructions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "video_urls" text,
    "image_urls" text,
    "description" text
);


alter table "public"."default_exercise_instructions" enable row level security;

create table "public"."exercise_instructions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "video_urls" text,
    "image_urls" text,
    "description" text,
    "therapist_uid" uuid not null
);


alter table "public"."exercise_instructions" enable row level security;

alter table "public"."default_exercises" drop column "default_exercise_instructions";

alter table "public"."default_exercises" add column "creator_username" text default 'Kymu'::text;

alter table "public"."default_exercises" add column "default_exercise_instruction_ids" bigint[] not null;

alter table "public"."default_exercises" add column "modality" exercise_modality;

alter table "public"."exercises" add column "exercise_instruction_ids" bigint[];

alter table "public"."exercises" add column "modality" exercise_modality;

alter table "public"."patient_sessions" drop column "modality";

drop type "public"."modality";

CREATE UNIQUE INDEX default_exercise_instructions_pkey ON public.default_exercise_instructions USING btree (id);

CREATE UNIQUE INDEX exercise_instructions_pkey ON public.exercise_instructions USING btree (id);

alter table "public"."default_exercise_instructions" add constraint "default_exercise_instructions_pkey" PRIMARY KEY using index "default_exercise_instructions_pkey";

alter table "public"."exercise_instructions" add constraint "exercise_instructions_pkey" PRIMARY KEY using index "exercise_instructions_pkey";

alter table "public"."exercise_instructions" add constraint "public_exercise_instructions_therapist_uid_fkey" FOREIGN KEY (therapist_uid) REFERENCES therapists(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."exercise_instructions" validate constraint "public_exercise_instructions_therapist_uid_fkey";

grant delete on table "public"."default_exercise_instructions" to "anon";

grant insert on table "public"."default_exercise_instructions" to "anon";

grant references on table "public"."default_exercise_instructions" to "anon";

grant select on table "public"."default_exercise_instructions" to "anon";

grant trigger on table "public"."default_exercise_instructions" to "anon";

grant truncate on table "public"."default_exercise_instructions" to "anon";

grant update on table "public"."default_exercise_instructions" to "anon";

grant delete on table "public"."default_exercise_instructions" to "authenticated";

grant insert on table "public"."default_exercise_instructions" to "authenticated";

grant references on table "public"."default_exercise_instructions" to "authenticated";

grant select on table "public"."default_exercise_instructions" to "authenticated";

grant trigger on table "public"."default_exercise_instructions" to "authenticated";

grant truncate on table "public"."default_exercise_instructions" to "authenticated";

grant update on table "public"."default_exercise_instructions" to "authenticated";

grant delete on table "public"."default_exercise_instructions" to "service_role";

grant insert on table "public"."default_exercise_instructions" to "service_role";

grant references on table "public"."default_exercise_instructions" to "service_role";

grant select on table "public"."default_exercise_instructions" to "service_role";

grant trigger on table "public"."default_exercise_instructions" to "service_role";

grant truncate on table "public"."default_exercise_instructions" to "service_role";

grant update on table "public"."default_exercise_instructions" to "service_role";

grant delete on table "public"."exercise_instructions" to "anon";

grant insert on table "public"."exercise_instructions" to "anon";

grant references on table "public"."exercise_instructions" to "anon";

grant select on table "public"."exercise_instructions" to "anon";

grant trigger on table "public"."exercise_instructions" to "anon";

grant truncate on table "public"."exercise_instructions" to "anon";

grant update on table "public"."exercise_instructions" to "anon";

grant delete on table "public"."exercise_instructions" to "authenticated";

grant insert on table "public"."exercise_instructions" to "authenticated";

grant references on table "public"."exercise_instructions" to "authenticated";

grant select on table "public"."exercise_instructions" to "authenticated";

grant trigger on table "public"."exercise_instructions" to "authenticated";

grant truncate on table "public"."exercise_instructions" to "authenticated";

grant update on table "public"."exercise_instructions" to "authenticated";

grant delete on table "public"."exercise_instructions" to "service_role";

grant insert on table "public"."exercise_instructions" to "service_role";

grant references on table "public"."exercise_instructions" to "service_role";

grant select on table "public"."exercise_instructions" to "service_role";

grant trigger on table "public"."exercise_instructions" to "service_role";

grant truncate on table "public"."exercise_instructions" to "service_role";

grant update on table "public"."exercise_instructions" to "service_role";