drop policy "Enable read access for all users" on "public"."exercises_default_templates";

drop policy "Enable read access for all users" on "public"."unit_default_templates";

revoke delete on table "public"."exercises_default_templates" from "anon";

revoke insert on table "public"."exercises_default_templates" from "anon";

revoke references on table "public"."exercises_default_templates" from "anon";

revoke select on table "public"."exercises_default_templates" from "anon";

revoke trigger on table "public"."exercises_default_templates" from "anon";

revoke truncate on table "public"."exercises_default_templates" from "anon";

revoke update on table "public"."exercises_default_templates" from "anon";

revoke delete on table "public"."exercises_default_templates" from "authenticated";

revoke insert on table "public"."exercises_default_templates" from "authenticated";

revoke references on table "public"."exercises_default_templates" from "authenticated";

revoke select on table "public"."exercises_default_templates" from "authenticated";

revoke trigger on table "public"."exercises_default_templates" from "authenticated";

revoke truncate on table "public"."exercises_default_templates" from "authenticated";

revoke update on table "public"."exercises_default_templates" from "authenticated";

revoke delete on table "public"."exercises_default_templates" from "service_role";

revoke insert on table "public"."exercises_default_templates" from "service_role";

revoke references on table "public"."exercises_default_templates" from "service_role";

revoke select on table "public"."exercises_default_templates" from "service_role";

revoke trigger on table "public"."exercises_default_templates" from "service_role";

revoke truncate on table "public"."exercises_default_templates" from "service_role";

revoke update on table "public"."exercises_default_templates" from "service_role";

revoke delete on table "public"."unit_default_templates" from "anon";

revoke insert on table "public"."unit_default_templates" from "anon";

revoke references on table "public"."unit_default_templates" from "anon";

revoke select on table "public"."unit_default_templates" from "anon";

revoke trigger on table "public"."unit_default_templates" from "anon";

revoke truncate on table "public"."unit_default_templates" from "anon";

revoke update on table "public"."unit_default_templates" from "anon";

revoke delete on table "public"."unit_default_templates" from "authenticated";

revoke insert on table "public"."unit_default_templates" from "authenticated";

revoke references on table "public"."unit_default_templates" from "authenticated";

revoke select on table "public"."unit_default_templates" from "authenticated";

revoke trigger on table "public"."unit_default_templates" from "authenticated";

revoke truncate on table "public"."unit_default_templates" from "authenticated";

revoke update on table "public"."unit_default_templates" from "authenticated";

revoke delete on table "public"."unit_default_templates" from "service_role";

revoke insert on table "public"."unit_default_templates" from "service_role";

revoke references on table "public"."unit_default_templates" from "service_role";

revoke select on table "public"."unit_default_templates" from "service_role";

revoke trigger on table "public"."unit_default_templates" from "service_role";

revoke truncate on table "public"."unit_default_templates" from "service_role";

revoke update on table "public"."unit_default_templates" from "service_role";

alter table "public"."exercises_default_templates" drop constraint "public_exercises_default_templates_default_exercise_id_fkey";


alter table "public"."unit_default_templates" drop constraint "public_training_blocks_therapist_templates_therapist_uid_fkey";

alter table "public"."exercises_default_templates" drop constraint "exercises_default_templates_pkey";

alter table "public"."unit_default_templates" drop constraint "training_blocks_therapist_templates_pkey";

drop index if exists "public"."exercises_default_templates_pkey";

drop index if exists "public"."training_blocks_therapist_templates_pkey";

drop table "public"."exercises_default_templates";

drop table "public"."unit_default_templates";

create table "public"."default_unit_templates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "default_exercises_index" bigint[] not null
);


alter table "public"."default_unit_templates" enable row level security;

alter table "public"."units" alter column "exercises_index" set not null;

CREATE UNIQUE INDEX training_blocks_therapist_templates_pkey ON public.default_unit_templates USING btree (id);

alter table "public"."default_unit_templates" add constraint "training_blocks_therapist_templates_pkey" PRIMARY KEY using index "training_blocks_therapist_templates_pkey";

grant delete on table "public"."default_unit_templates" to "anon";

grant insert on table "public"."default_unit_templates" to "anon";

grant references on table "public"."default_unit_templates" to "anon";

grant select on table "public"."default_unit_templates" to "anon";

grant trigger on table "public"."default_unit_templates" to "anon";

grant truncate on table "public"."default_unit_templates" to "anon";

grant update on table "public"."default_unit_templates" to "anon";

grant delete on table "public"."default_unit_templates" to "authenticated";

grant insert on table "public"."default_unit_templates" to "authenticated";

grant references on table "public"."default_unit_templates" to "authenticated";

grant select on table "public"."default_unit_templates" to "authenticated";

grant trigger on table "public"."default_unit_templates" to "authenticated";

grant truncate on table "public"."default_unit_templates" to "authenticated";

grant update on table "public"."default_unit_templates" to "authenticated";

grant delete on table "public"."default_unit_templates" to "service_role";

grant insert on table "public"."default_unit_templates" to "service_role";

grant references on table "public"."default_unit_templates" to "service_role";

grant select on table "public"."default_unit_templates" to "service_role";

grant trigger on table "public"."default_unit_templates" to "service_role";

grant truncate on table "public"."default_unit_templates" to "service_role";

grant update on table "public"."default_unit_templates" to "service_role";

create policy "Enable read access for all users"
on "public"."default_unit_templates"
as permissive
for select
to authenticated
using (true);

